### ISSUE TITLE
[FEAT] Click Event2

### ISSUE THREAD

**Issue by leesumin0526** [ssu-User-Interface/Booking#32]
## TO-DO ✏️
- [x] Login Activity
        - [ ] 로그인 버튼(tv_login_login) : Home fragment로 이동
        - [ ] 회원가입 버튼(tv_login_signup) : Signup fragment로 이동

- [x] Signup Fragment
        - [ ] 회원가입 버튼(tv_signup_signup) : Signup fragment로 이동

- [ ] Home Fragment
        - [ ] 읽고있는 책 존재
                     - [ ] 첫번째 위젯 타이머 버튼 (view_home_first_widget_right_add_book ) : fragment_timer로 이동
                     - [ ] tv_home_first_widget_book_title, view_home_line, tv_home_first_widget_reading_period, tv_home_first_widget_reading_page, prg, view_home_first_widget_right_to_timer : visibility = "visible" / iv_home_book_ic, tv_home_first_widget_no_book, view_home_first_widget_right_add_book : visibility = "gone"
        - [ ] 읽고있는 책 존재 X /  첫번째 위젯 책 추가 버튼 (view_home_first_widget_right_add_book) : fragment_book_search로 이동
       
- [ ] Record Fragment
        - [ ] 읽을 책 / 읽는 책 / 읽은 책 (tv_record_read/ tv_record_read / tv_record_read) : data 구분
        - [ ] 책 추가하기 버튼 (btn_record_add_book) : fragment_book_search로 이동
        
- [ ] Record Specific Fragment
        - [ ] 독서 시작하기 버튼 (btn_specific_record_start_reading) : fragment_timer로 이동
        - [ ] 뒤로가기 버튼 (iv_back_arrow) : fragment_record로 이동

- [ ] Timer Fragment
        - [ ] 독서 그만하기 버튼 (ic_timer_x_btn) : fragment_recored_specific으로 이동
        - [ ] 시작 / 정지 버튼 (view_timer_round , tv_timer_start): 토글로 tv_timer_start의 text "정지" / "시작"으로 변경
