### ISSUE TITLE
[FEAT] 책 검색 Click Event 기능 구현

### ISSUE THREAD

**Issue by hyowon0204** [ssu-User-Interface/Booking#46]
## TO-DO ✏️
- [x] 홈 화면 페이지 <-> 책 검색 페이지로 네비게이션 화면 전환으로 수정
- [x] 책 검색 페이지 <-> 책 상세 페이지로 네비게이션 화면 전환으로 수정
- [x] 책 상세 페이지 <-> 책 저장 바텀 시트 페이지로 네비게이션 화면 전환으로 수정
