### ISSUE TITLE
[UI] 검색 페이지 UI 수정

### ISSUE THREAD

**Issue by hyowon0204** [ssu-User-Interface/Booking#48]
## TO-DO ✏️
- [x] 검색 페이지들 배경 수정
- [x] 책 검색 아이템 배경 수정
- [x] 바텀 시트 배경 투명화 작업
