### ISSUE TITLE
[FEAT] MVVM 구조로 API 연동 준비

### ISSUE THREAD

**Issue by hyowon0204** [ssu-User-Interface/Booking#64]
## TO-DO ✏️
- [x] MVVM 구조로 API 연동 준비
   - [x] Hilt 의존성 주입
   - [x] Module 생성(네이버 도서 검색 open API base_url 및 client_id,secret 설정)
   - [x] mvvm 구조로 데이터 관여 파일들 생성
   - [x] API 연결 후 ViewModel로 UI 적용
