### ISSUE TITLE
[Feat] DB 연결 기능들 구현

### ISSUE THREAD

**Issue by leesumin0526** [ssu-User-Interface/Booking#74]
## TO-DO ✏️
- [x] 해당하는 책의 타이머 페이지로 이동 및 값 전달
- [x] 기록 상세보기에서 memo 띄우기
- [x] 홈화면 위젯 xml 수정
- [x] 총 독서 기간 위젯 + 총 독서 시간 구현
- [x] Record listview 맨 아래 안 보이는 거 수정
- [x] 기록 작성하기로 넘어갈 때 해당하는 책에 대한 기록으로 이동
